server:
  port: 80
  servlet:
    context-path: /
  tomcat:
    basedir: /data/apps/temp
spring:
  datasource:
    url: jdbc:mysql://*****:3306/time_circle?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: ******
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB